name: Update Qiita Posts

on:
  schedule:
    - cron: "0 */6 * * *"   # 6æ™‚é–“ã”ã¨
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ============================
      # Qiita Pickup Articles
      # ============================
      - name: Fetch Qiita Pickup Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://qiita.com/tags/pickup/feed.atom"
          comment_tag_name: "QIITA-PICKUP"
          max_post_count: 3
          template: |
            <sub></sub>
            - ğŸš€ **[$title]($url)**
              - ğŸ· $categories
              - ğŸŒŸ Qiita Pickup

      # ============================
      # Recent Qiita Articles
      # ============================
      - name: Fetch Recent Qiita Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://qiita.com/Necoze/feed.atom"
          comment_tag_name: "QIITA-POSTS"
          max_post_count: 5
          template: |
            <sub></sub>
            - ğŸ“ **[$title]($url)**  
            <sub></sub>
